news_collecting:
  description: >
    Search for and summarize the 3 most impactful news articles affecting the global crypto market — particularly
    Bitcoin and Ethereum — from the past 3 months as of today ({current_date}).


    Workflow:
    1. Formulate 2–3 specific and effective search queries related to recent macroeconomic or global financial policy
      news that significantly impacts the crypto market (e.g., "interest rate hikes and crypto impact", "inflation and
      Bitcoin price", etc.).
    2. Use `SerperDevTool` to search for: "macroeconomic events affecting cryptocurrency July 2024 to July 2025"
      and "global financial policy news affecting Bitcoin and Ethereum July 2024 to July 2025".
      Ensure the search results are relevant to the global crypto market, focusing on Bitcoin and Ethereum.
    3. Select the 3 most influential articles based on impact, credibility, and relevance to the global crypto market.
      DO NOT include sources from vietstock.vn.
    4. Use `ScrapeWebsiteTool` to extract full content from the selected articles. DO NOT scrape vietstock.vn.
    5. Summarize each article in 3–5 sentences, focusing on how the news affects the crypto market,
      especially BTC & ETH.


    Constraints:
    - Only select articles published within the past 3 months.
    - DO NOT use or refer to content from vietstock.vn.
    - Choose articles that clearly influence the global financial/crypto market.
    - You must not fabricate or invent any content. All output must be based on tool-extracted data.

  expected_output: >
    A markdown list of 3 items, each containing:
    - **Article Title**
    - Publication Date
    - Source (with URL)
    - Summary (3–5 sentences in English focusing on the impact on Bitcoin and Ethereum)

  agent: crypto_news_researcher
